import Link from "next/link";
import { GROUP_LABELS, GROUP_WEIGHTS, METRIC_SPECS, PSL_MODEL_VERSION, SCORE_CURVE, SYMMETRY_REF } from "@/lib/psl/version";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="panel p-6">
      <h2 className="mb-3 text-lg font-bold text-gold-400">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-white/65">{children}</div>
    </section>
  );
}

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-6 py-10">
      <div>
        <h1 className="text-3xl font-black">Scoring Methodology</h1>
        <p className="mt-2 text-sm text-white/45">
          Full transparency for model <span className="font-mono text-gold-400">{PSL_MODEL_VERSION}</span>. Every
          constant below is pinned in source; the model hash recorded with each scan locks it to exactly these
          numbers.
        </p>
      </div>

      <Section title="What PSL is — and is not">
        <p>
          PSL is a <strong className="text-white">facial-analysis score generated by this platform</strong>. It is a
          deterministic measurement of facial geometry against stylized classical canons (rule of thirds, rule of
          fifths, neoclassical proportions). It is reproducible and auditable.
        </p>
        <p>
          It is <strong className="text-white">not</strong> an objective measurement of human worth, not a
          scientifically universal attractiveness rating, and not a verdict. Reference values are sex-neutral
          averages; different populations and different canons would produce different numbers, and that is fine.
        </p>
        <p>
          If a capture cannot be measured honestly, the platform demands a rescan. <strong className="text-white">We never fabricate precision.</strong>
        </p>
      </Section>

      <Section title="Perception engine (open-source, on-device)">
        <p>
          Facial geometry is extracted by <strong className="text-white">@vladmandic/human</strong> — the
          MIT-licensed, actively maintained TensorFlow.js face-analysis engine (successor of face-api.js).
          It runs entirely in your browser: BlazeFace detection, a 468-point face mesh plus 10 iris points,
          true 3D head rotation (pitch/yaw/roll), and built-in <strong className="text-white">liveness</strong> and{" "}
          <strong className="text-white">anti-spoof</strong> confidence models.
        </p>
        <p className="mt-2">
          The engine only <em>measures</em>. The score itself never comes from the engine or from any neural
          rating — it is computed by the pinned deterministic pipeline below. If the engine cannot initialize
          on a device, the platform transparently falls back to the MediaPipe FaceLandmarker engine; both
          produce the same 478-point topology the scoring layer consumes.
        </p>
      </Section>

      <Section title="Pipeline (deterministic, no black box)">
        <ol className="list-decimal space-y-2 pl-5">
          <li><strong className="text-white">Capture.</strong> 18 video frames that pass all quality gates (frontal pose, lighting, sharpness, single face).</li>
          <li><strong className="text-white">Stabilize.</strong> Per-landmark median across frames rejects micro-movement and blinks.</li>
          <li><strong className="text-white">Normalize.</strong> Landmarks are transformed into a canonical frame: origin at the inter-iris midpoint, unit = interpupillary distance, iris line rotated horizontal. This removes camera distance, translation and roll; near-frontal gating bounds residual perspective error.</li>
          <li><strong className="text-white">Measure.</strong> 13 dimensionless metrics + a bilateral symmetry index are computed from the normalized constellation.</li>
          <li><strong className="text-white">Standardize.</strong> Each metric becomes z = (value − reference mean) / reference SD, clamped.</li>
          <li><strong className="text-white">Score groups.</strong> Per group: score = {SCORE_CURVE.base} + {SCORE_CURVE.span}·exp(−rmsZ²/{SCORE_CURVE.falloff}).</li>
          <li><strong className="text-white">Combine.</strong> Weighted mean of groups → final /10, clamped to [0.5, 9.8] because landmark-only analysis cannot honestly reach extremes.</li>
        </ol>
        <p>No randomness anywhere after capture. Same landmarks → same score, forever, for this model version.</p>
      </Section>

      <Section title="Components & weights">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-white/10 text-[10px] uppercase tracking-widest text-white/35">
                <th className="py-2 pr-3">Group (weight)</th>
                <th className="py-2 pr-3">Metric</th>
                <th className="py-2 pr-3">Reference μ</th>
                <th className="py-2">Reference σ</th>
              </tr>
            </thead>
            <tbody>
              {METRIC_SPECS.map((m) => (
                <tr key={m.key} className="border-b border-white/[0.05]">
                  <td className="py-2 pr-3 align-top text-white/50">
                    {GROUP_LABELS[m.group]} <span className="text-gold-400">{Math.round(GROUP_WEIGHTS[m.group] * 100)}%</span>
                  </td>
                  <td className="py-2 pr-3 text-white/80">{m.label}</td>
                  <td className="py-2 pr-3 font-mono">{m.refMean}</td>
                  <td className="py-2 font-mono">{m.refSd}</td>
                </tr>
              ))}
              <tr>
                <td className="py-2 pr-3 text-white/50">
                  {GROUP_LABELS.symmetry} <span className="text-gold-400">{Math.round(GROUP_WEIGHTS.symmetry * 100)}%</span>
                </td>
                <td className="py-2 pr-3 text-white/80">Mean mirrored landmark deviation</td>
                <td className="py-2 pr-3 font-mono">{SYMMETRY_REF.refMean}</td>
                <td className="py-2 font-mono">{SYMMETRY_REF.refSd}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="text-xs text-white/40">
          Note: the hairline is not a mesh landmark; the upper third uses a documented extrapolation and carries a
          reduced z-clamp. Gonion/jaw-angle points are mesh approximations. Such limits are why margins are generous
          and why scores are presented with confidence, not false exactness.
        </p>
      </Section>

      <Section title="Normalization & quality gates">
        <ul className="list-disc space-y-1 pl-5">
          <li>Head rotation: scans require |yaw| ≤ 10°, |roll| ≤ 7°; pose is estimated from iris position inside the eye aperture.</li>
          <li>Camera distance: all metrics are scale-free ratios; the canonical frame additionally uses IPD as its unit.</li>
          <li>Lighting: face-crop luminance must sit in 50–215 with sufficient contrast.</li>
          <li>Image quality: Laplacian-variance sharpness on a 96px face crop; blur, missed focus and compressed replay footage fail.</li>
          <li>Stability: inter-frame landmark jitter is measured and folded into confidence.</li>
        </ul>
        <p>Confidence = weighted blend of presence, stability, sharpness, lighting, pose and frame yield. Below 62% no score is issued — rescan required.</p>
      </Section>

      <Section title="Liveness & anti-cheat">
        <ul className="list-disc space-y-1 pl-5">
          <li>Server-issued challenge sequence with <strong className="text-white">randomized order</strong> (straight → shuffled left/right/blink → neutral) — static images fail; pre-recorded clips cannot anticipate the order.</li>
          <li>Per-challenge timing windows; evidence (yaw traces, EAR dip, presence) validated server-side.</li>
          <li>Exactly one face required; extra faces reject the frame.</li>
          <li>Screen/replay heuristics: sharpness + contrast gates, challenge-response latency, and a one-way capture digest compared across all scans — the same capture signature from another account is rejected and flagged.</li>
          <li>Battle scores must come from the pinned model (version + constant hash), include complete components, and pass the same quality gates.</li>
          <li>Battle score diverging &gt; 2.0 from the verified scan flags the match; flagged matches have Elo gains halved and are logged.</li>
          <li>Rate limits on sessions, scans and reports; auto-flag on repeated reports.</li>
        </ul>
      </Section>

      <Section title="Fair matchmaking & Elo">
        <ul className="list-disc space-y-1 pl-5">
          <li>Randomized queues for Ranked 1v1, Casual 1v1 and Random Duo (solo join → random teammate).</li>
          <li>No immediate rematches: 30-minute pair cooldown in random queues, plus a 3-per-day cap per opponent pair.</li>
          <li>Mutual blocking always prevents pairing.</li>
          <li>Standard Elo (K=32) against the opponent&apos;s (or opposing team&apos;s average) rating. Friend challenges are casual — no rating impact.</li>
        </ul>
      </Section>

      <Section title="Privacy">
        <ul className="list-disc space-y-1 pl-5">
          <li>All face processing runs on-device (@vladmandic/human engine, MediaPipe fallback). No images or video are transmitted or stored.</li>
          <li>Stored: score components, quality metrics, model version, and a one-way capture digest. The digest cannot be reversed into a face.</li>
          <li>Biometric templates are never exposed publicly and never shared between players.</li>
        </ul>
      </Section>

      <div className="flex justify-center gap-3 pt-2">
        <Link href="/lab" className="btn-gold">Try the Calibration Lab</Link>
        <Link href="/play" className="btn-ghost">Enter the Arena</Link>
      </div>
    </div>
  );
}
