import type { Metadata, Viewport } from "next";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/800.css";
import "@fontsource/inter/900.css";
import "@fontsource/jetbrains-mono/500.css";
import "@fontsource/jetbrains-mono/700.css";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "MOGBATTLE — PSL /10 Ranked Face-Battle Arena",
  description:
    "Deterministic, liveness-verified facial analysis scored out of 10, then head-to-head P2P battles with honest Elo. Trust-first competitive platform.",
};

export const viewport: Viewport = {
  themeColor: "#06070b",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen font-sans">
        <Nav />
        <main className="mx-auto w-full max-w-6xl px-4 pb-20">{children}</main>
        <footer className="border-t border-white/5 py-8 text-center text-xs text-white/35">
          <div className="mx-auto max-w-3xl space-y-2 px-4">
            <p>
              PSL is a facial-analysis score generated by this platform&apos;s geometric pipeline. It is{" "}
              <span className="text-white/60">not</span> a scientific constant, not a universal attractiveness
              standard and never a measurement of human worth.
            </p>
            <p>
              Face processing happens on your device. We never store or transmit face images — only non-identifying
              score components, quality metrics and a one-way capture signature.
            </p>
            <p className="text-white/25">MOGBATTLE · scoring model PSL-2026.1.0 · play responsibly</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
